spring:
  messages:
    basename: messages
    encoding: UTF-8
  application:
    name: transportation-service

  datasource:
    url: jdbc:postgresql://localhost:5432/transportation
    username: transportation_user
    password: transportation_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.default_batch_fetch_size: 50

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
logging:
  level:
    liquibase: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.springframework.boot.autoconfigure.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

security:
  jwt:
    issuer: "VerySecureIssuer"
    secret: "CHANGE_ME_very_long_random_secret_min_32_chars"
    access-token-ttl-minutes: 60
